name: CI/CD for Latex Resume PDF Building

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Latex
      run: sudo apt-get install texlive-full
    - name: Build PDF
      run: pdflatex resume.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: resume
        path: resume.pdf
